(use-package org
  :defer t
  :config
  (add-to-list 'auto-mode-alist '("\\.org$" . org-mode))
;;  (define-key global-map "C-c C-l" 'org-store-link)
;;  (define-key global-map "\C-ca" 'org-agenda)
  (setq org-list-indent-offset 10)
  (setq org-adapt-indentation nil)
  (setq org-agenda-files (quote ("/Users/dmarvin/local/orgs/todo.org")))
  (define-key global-map (kbd "C-c a") 'org-agenda)
  (setq org-highest-priority ?A)
  (setq org-lowest-priority ?C)
  (setq org-default-priority ?A)
  (setq org-priority-faces '((?A . (:foreground "#F0DFAF" :weight bold))
                             (?B . (:foreground "LightSteelBlue"))
                             (?C . (:foreground "OliveDrab"))))
  (setq org-agenda-window-setup (quote current-window))
  (define-key global-map (kbd "C-c c") 'org-capture)
  (setq org-capture-templates
        '(("t" "todo" entry (file+headline "/Users/dmarvin/local/orgs/todo.org" "Tasks")
           "* TODO [#A] #?")))
  (setq org-todo-keyword-faces '(("DONE"      . (:foreground "#afd8af"     :weight bold))
                                 ("WAITING"   . (:foreground "dark salmon" :weight bold))
                                 ("CANCELLED" . (:foreground "dim gray"    :weight bold))
                                 ("BUY"       . (:foreground "goldenrod"   :weight bold))
                                 ("HOWTO"     . (:foreground "SkyBlue3"    :weight bold))
                                 ("INFO"      . (:foreground "khaki1"      :weight bold))
                                 ("COLLECT"   . (:foreground "MediumSeaGreen" :weight bold))
                                 ("SOLVE"     . (:foreground "orange red"    :weight bold))
                                 ))
  )
