# coding: utf-8
cask_args appdir: '/Applications'

tap 'homebrew/bundle' || true

# https://github.com/d12frosted/homebrew-emacs-plus
tap 'd12frosted/emacs-plus' || true

brew 'git'
brew 'ag', args: '--HEAD'
brew 'aspell'
brew 'coreutils'
brew 'grc'

brew 'emacs-plus@28', args: '--with-modern-sjrmanning-icon'

